### ISSUE TITLE
Release 8.1.0?

### ISSUE THREAD

**Issue by rcthomas** [conda-forge/jupyterlab-h5web-feedstock#17]
### Comment:

Sorry I can't quite figure out the process to be able to release an older version, but recently a fix was applied to version 8 that still supports JupyterLab 3.x (8.1).  Would it be possible to trigger a release of 8.1 on conda-forge?  Thanks.

**Comment by t20100** [comment]
Hi,

Sure, I'll do it.
FYI, this is achieved by pushing to a separate branch on the repository: https://conda-forge.org/docs/maintainer/updating_pkgs/#maintaining-several-versions

**Comment by rcthomas** [comment]
Thanks!
